version: "3.10"

services:
  pg:
    image: postgres:latest
    container_name: qr-db
    restart: always
    env_file:
      - .env

    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    container_name: qr
    volumes:
      - .:/core
      - ./media:/app/media
    ports:
      - "8010:8000"
    command: bash -c "python manage.py showmigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - pg
    restart: always